server:
  port: 8002
  servlet:
    session:
          timeout: 600000
    context-path: /
spring:
  application:
      name: wx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wlm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
#  redis:
#    port: 6379
#    host: 127.0.0.1
#    password:
#    database: 0
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    multiple-result-sets-enabled: false
  mapper-locations: classpath*:mapper/*/*.xml

knife4j:
  enable: true

# 改设置可使用日志打印sql语句但不打印查询结果
logging:
  level:
    com.wlm.wlm.*: debug